### ISSUE TITLE
Know when a session opens

### ISSUE THREAD

**Issue by SwiTool** [stephenwvickers/node-net-snmp#32]
Hi,

if my PDU is disconnected, then, when I close my session it breaks the program because i'm doing : 

```javascript
  process.on('SIGINT', this.session.close.bind(this.session));
```

But the session was not opened : 
```
^Cdgram.js:638
    throw new errors.Error('ERR_SOCKET_DGRAM_NOT_RUNNING');
    ^

Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at Socket._healthCheck (dgram.js:638:11)
    at Socket.close (dgram.js:516:8)
    at Session.close (/Users/xxx/Documents/xxx/projets/Kobalt/node_modules/net-snmp/index.js:602:13)
    at emitNone (events.js:105:13)
    at process.emit (events.js:207:7)
    at Signal.wrap.onsignal (internal/process.js:205:44)
```

**Comment by stephenwvickers** [comment]
That seems like a bad idea, since you have no control over how many SIGINT signals will be sent to your process.  You should simply close() sockets when you are finished with when, you don't need to close() them when you program exits, your operating system will do that for you.

**Comment by SwiTool** [comment]
Okay thanks :)
